applicationController:
  containerPort: 8082
  servicePort: 8082
  image:
    repository: argoproj/argocd
    tag: v1.1.2
    pullPolicy: Always
  volumeMounts: []
  volumes: []

server:
  containerPort: 8080
  containerMetricsPort: 8083
  servicePortHttp: 80
  servicePortHttps: 443
  servicePortMetrics: 8083
  serviceAnnotations: {}
  metricsServiceAnnotations: {}
  image:
    repository: argoproj/argocd
    tag: v1.1.2
    pullPolicy: Always
  uiInitImage:
    repository: argoproj/argocd-ui
    tag: v1.1.2
    pullPolicy: Always
  extraArgs: []
  volumeMounts: []
  volumes: []
  annotations: {}

repoServer:
  containerPort: 8081
  servicePort: 8081
  metricsPort: 8084
  image:
    repository: argoproj/argocd
    tag: v1.1.2
    pullPolicy: Always
  volumeMounts: []
  volumes: []
  sshKnownHosts:
    - domain: bitbucket.org
      type: ssh-rsa
      key: AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
    - domain: github.com
      type: ssh-rsa
      key: AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
    - domain: gitlab.com
      type: ecdsa-sha2-nistp256
      key: AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
    - domain: gitlab.com
      type: ssh-ed25519
      key: AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
    - domain: github.com
      type: ssh-rsa
      key: AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9
    - domain: ssh.dev.azure.com
      type: ssh-rsa
      key: AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
    - domain: vs-ssh.visualstudio.com
      type: ssh-rsa
      key: AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H   

dexServer:
  containerPortHttp: 5556
  containerPortGrpc: 5557
  servicePortHttp: 5556
  servicePortGrpc: 5557
  image:
    repository: quay.io/dexidp/dex
    tag: v2.14.0
    pullPolicy: Always
  initImage:
    repository: argoproj/argocd
    tag: v1.1.2
    pullPolicy: Always
  volumeMounts: []
  volumes: []

# terminate tls at ArgoCD level
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  path: /
  hosts:
    - argocd.example.com

# Standard Argo CD installation with cluster-admin access.
# Set this true if you plan to use Argo CD to deploy applications in the same cluster that
#     Argo CD runs in (i.e. kubernetes.svc.default).
# Will still be able to deploy to external clusters with inputted credentials.

clusterAdminAccess:
  enabled: true
  minimalPrivileges: true

config:
  helmRepositories:
    # - name: privateRepo
    #   url: http://chartmuseum.privatecloud.com
    #   usernameSecret:
    #     name: private-chartmuseum
    #     key: username
    #   passwordSecret:
    #     name: private-chartmuseum
    #     key: password
    # - name: incubator
    #   url: https://kubernetes-charts-incubator.storage.googleapis.com/
  repositories:
    # - url: git@gitlab.com:usersprivategroup/users-gitops-config.git
    #   sshPrivateKeySecret:
    #     key: privateKey
    #     name: argocd-dev-key
    # - url: git@gitlab.com:accountingprivategroup/accounting-gitops-config.git
    #   sshPrivateKeySecret:
    #     key: privateKey
    #     name: argocd-dev-key
  dexConfig:
    #   # Argo CD's externally facing base URL. Required for configuring SSO
    #   # url: https://argo-cd-demo.argoproj.io
    #
    #   # A dex connector configuration. See documentation on how to configure SSO:
    #   # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/sso.md#2-configure-argo-cd-for-sso
    # connectors:
    #   # GitHub example
    #   - type: github
    #     id: github
    #     name: GitHub
    #     config:
    #       clientID: aabbccddeeff00112233
    #       clientSecret: $dex.github.clientSecret
    #       orgs:
    #       - name: your-github-org
    #         teams:
  url: # https://argocd.example.com/
  oidcConfig:
    # name: Okta
    # issuer: https://dev-123456.oktapreview.com
    # clientID: aaaabbbbccccddddeee
    # clientSecret: $oidc.okta.clientSecret
  # The following keys hold the shared secret for authenticating GitHub/GitLab/BitBucket webhook
  # events. To enable webhooks, configure one or more of the following keys with the shared git
  # provider webhook secret. The payload URL configured in the git provider should use the
  # /api/webhook endpoint of your Argo CD instance (e.g. https://argocd.example.com/api/webhook)
  webhook:
    githubSecret:
    gitlabSecret:
    bitbucketSecret:
  # resourceCustomizations can be used to create custom health checks for resources
  # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/health.md#way-1-define-a-custom-health-check-in-argocd-cm-configmap
  resourceCustomizations:
  #   certmanager.k8s.io/Certificate:
  #     health.lua: |
  #       hs = {}
  #       ...
  #       return hs
  configManagementPlugins:
    # - name: pluginName
    #   init:                          # Optional command to initialize application source directory
    #     command: ["sample command"]
    #     args: ["sample args"]
    #   generate:                      # Command to generate manifests YAML
    #     command: ["sample command"]
    #     args: ["sample args"]

rbac:
#   # An RBAC policy .csv file containing additional policy and role definitions.
#   # See https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/rbac.md on how to write RBAC policies.
#   policy.csv: |
#     # Give all members of "my-org:team-alpha" the ability to sync apps in "my-project"
#     p, my-org:team-alpha, applications, sync, my-project/*, allow
#     # Make all members of "my-org:team-beta" admins
#     g, my-org:team-beta, role:admin
  policyCsv: #|
  #   p, role:org-admin, applications, *, */*, allow
  #   p, role:org-admin, clusters, get, *, allow
  #   p, role:org-admin, repositories, get, *, allow
  #   p, role:org-admin, repositories, create, *, allow
  #   p, role:org-admin, repositories, update, *, allow
  #   p, role:org-admin, repositories, delete, *, allow
  #   g, your-github-org:your-team, role:org-admin
  # The default role Argo CD will fall back to, when authorizing API requests
  policyDefault: #role:readonly
  # Scopes controls which OIDC scopes to examine during rbac enforcement (in addition to `sub` scope).
  scopes: #[groups]

redis:
  image:
    repository: redis
    tag: 5.0.3
    pullPolicy: Always
  containerPort: 6379
  servicePort: 6379
