apiVersion: v1
kind: Service
metadata:
  name: argocd-server-metrics
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-server-metrics
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ include "argo-cd.name" . }}
    app.kubernetes.io/component: server
  {{- if .Values.server.metricsServiceAnnotations }}
  annotations:
{{ toYaml .Values.server.metricsServiceAnnotations | indent 4}}{{- end }}
spec:
  ports:
  - name: metrics
    protocol: TCP
    port: {{ .Values.server.servicePortMetrics }}
    targetPort: {{ .Values.server.containerMetricsPort }}
  selector:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}-server
