apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-tls-certs-cm
  labels:
    app.kubernetes.io/name: {{ include "argo-cd.name" . }}
    helm.sh/chart: {{ include "argo-cd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ include "argo-cd.name" . }}
data: null
